import React from 'react';
import styles from './transactionsAndBlocks.css';

const Blocks = ({
  t, blocks, onSelectedRow, updateRowItemIndex,
}) => (
  <div className={`${styles.wrapper} blocks`}>
    <header className={`${styles.header} blocks-header`}>
      <div className={`${styles.subTitles} blocks-subtitles`}>
        <label>{t('Block ID')}</label>
        <label>{t('Generated by')}</label>
      </div>
    </header>
    <div className={`${styles.content} blocks-content`}>
      {blocks.map((block, i) => (
        <div
          key={block.id}
          data-index={i}
          className={`${styles.resultRow} search-block-row`}
          onMouseEnter={updateRowItemIndex}
          onClick={() => onSelectedRow(block.id)}
        >
          <span>{block.id}</span>
          <span>{block.generatorUsername}</span>
        </div>
      ))}
    </div>
  </div>
);

export default Blocks;
